- name: Setting up development environment
  hosts: localhost
  gather_facts: true
  become: false

  vars_files:
    - ansible/packages.yml
    - ansible/dots.yml
  
  tasks:
    - name: Install packages for WSL
      include_tasks: ansible/windows/dev.yml
      when:
        - ansible_facts['virtualization_type'] == "wsl"

    - name: Setup dotfiles
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'
      loop: "{{ dots_common }}"
      when: item.src is defined and item.dest is defined