- name: Setting up development environment for Arch Linux
  hosts: localhost
  gather_facts: true
  become: false

  vars_files:
    - packages.yml
    - dots.yml

  tasks:
  - name: Perform common prerequisite tasks
    include_tasks: ./common.yml

  - name: Install AUR packages using yay
    shell: yay -S --noconfirm --needed {{ item }}
    loop: "{{ dev_packages }}"
    ignore_errors: yes
    register: package_result

  - name: Warning about missing packages
    ansible.builtin.debug:
      msg: "Package {{ item }} could not be installed"
    loop: "{{ package_result.results | selectattr('failed', 'eq', true) | map(attribute='item') | list }}"
    when: package_result.results | selectattr('failed', 'eq', true) | list | length > 0

  - name: Ensure wireshark group exists
    become: yes
    group:
      name: wireshark
      state: present

  - name: Add user to wireshark group
    become: yes
    user:
      name: vedant   
      groups: wireshark
      append: yes

  - name: Set Git user.name
    ansible.builtin.command:
      cmd: git config --global user.name "Vedant Wankhade"

  - name: Set Git user.email
    ansible.builtin.command:
      cmd: git config --global user.email "vedantwankhade17@gmail.com"

  - name: Setup dotfiles
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/{{ item.src }}"
      dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: '0755'
    loop: "{{ dev_dots }}"
    when: item.src is defined and item.dest is defined
