dev_packages_common:
  - git
  - neovim

dev_packages_ubuntu:
  - luarocks
  - golang
  - gopls
 
dev_packages_arch:
  - go
  - gopls
  - visual-studio-code-bin
  - luarocks
  - zen-browser-bin
  - bluez
  - bluez-utils
  - blueman
  - pavucontrol
  - brightnessctl
  - playerctl
  - syncthing
  - fuse
  - kitty
  - dolphin
  - ark
  - wofi
  - superproductivity-bin
  - spotify
  - hyprland
  - actual-appimage
  - hyprpaper
  - kitty
  - xdg-desktop-portal-hyprland
  - qt5-wayland
  - qt6-wayland
  - polkit-kde-agent

dev_packages_fedora:
  - 

dev_packages_nix:
  - 

dev_packages_macos:
  - 

extra_packages_common:
  - 

extra_packages_windows:
  - 

extra_packages_ubuntu:
  -